"""
Vehicle API Client
==================
Client for the BL4B vehicle registration/deregistration platform partner API.

Endpoints:
    POST /bl4b/v1/vehicle/register     — register one or more VINs
    POST /bl4b/v1/vehicle/deregister   — deregister one or more VINs

Authentication:
    x-api-key header — value read from VEHICLE_API_KEY env var (NEVER hardcoded).

Configuration:
    Base URL comes from config.yaml environments.<env>.vehicle_api_url.
    Falls back to VEHICLE_API_BASE_URL env var, then raises if neither set.

Transaction IDs:
    Every outbound request must carry a unique transactionId (UUID4).
    Use ``generate_transaction_id()`` — the single place in this module where
    IDs are produced.  The function is called explicitly *before* the request
    body is constructed so the ID appears in logs and Allure before the HTTP
    call fires.

    Example — two consecutive calls produce different IDs:
        generate_transaction_id()  →  "64a1a656-130c-4aec-8a04-b73b3d2515e0"
        generate_transaction_id()  →  "64a1a656-130c-4aec-8a04-b73b3d2679e0"

Usage::

    from utils.api.vehicle_client import VehicleAPIClient
    client = VehicleAPIClient.from_config(config)

    resp = client.register_vehicles(
        partner_code="HBL4BP-006",
        vin_list=["KMUHCESC7RU179347"],
    )
    assert resp.status_code == 200

Environment variables:
    VEHICLE_API_KEY        — x-api-key header value  (required for real calls)
    VEHICLE_API_BASE_URL   — override base URL (optional, prefers config.yaml)
"""
from __future__ import annotations

import os
import uuid
from dataclasses import dataclass
from typing import Any

from utils.api.base_client import APIResponse, BaseAPIClient
from utils.logger import log_info_emoji, log_warning

# ---------------------------------------------------------------------------
# Constants — env-var names only
# ---------------------------------------------------------------------------

_API_KEY_ENV      = "VEHICLE_API_KEY"
_BASE_URL_ENV     = "VEHICLE_API_BASE_URL"

_REGISTER_PATH   = "bl4b/v1/vehicle/register"
_DEREGISTER_PATH = "bl4b/v1/vehicle/deregister"


# ---------------------------------------------------------------------------
# Transaction ID generator — the ONLY place in this module that creates IDs
# ---------------------------------------------------------------------------

def generate_transaction_id() -> str:
    """
    Generate a fresh UUID4 string suitable for use as a request transactionId.

    Called explicitly *before* each request body is constructed, so the
    generated value is visible in logs and Allure *before* the HTTP call fires.

    Returns:
        A lowercase hyphenated UUID4 string, e.g.
        ``"64a1a656-130c-4aec-8a04-b73b3d2679e0"``

    Every call returns a value that differs from the previous one::

        generate_transaction_id()  →  "64a1a656-130c-4aec-8a04-b73b3d2515e0"
        generate_transaction_id()  →  "64a1a656-130c-4aec-8a04-b73b3d2679e0"
    """
    return str(uuid.uuid4())


# ---------------------------------------------------------------------------
# Request models (dataclasses — no Pydantic dependency)
#
# transaction_id has NO default here — it must be passed in explicitly by the
# caller (always via generate_transaction_id()).  This makes the generation
# step visible in client code and easy to intercept in tests.
# ---------------------------------------------------------------------------


@dataclass
class VehicleRegistrationRequest:
    transaction_id: str        # generated by generate_transaction_id() — no default
    partner_code: str
    vin_list: list[str]

    def to_dict(self) -> dict:
        return {
            "transactionId": self.transaction_id,
            "partnerCode":   self.partner_code,
            "vinList":       [{"vin": v} for v in self.vin_list],
        }


@dataclass
class VehicleDeregistrationRequest:
    transaction_id: str        # generated by generate_transaction_id() — no default
    partner_code: str
    vin_list: list[str]

    def to_dict(self) -> dict:
        return {
            "transactionId": self.transaction_id,
            "partnerCode":   self.partner_code,
            "vinList":       [{"vin": v} for v in self.vin_list],
        }


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class VehicleAPIClient(BaseAPIClient):
    """
    Platform partner client for BL4B vehicle registration API.

    All public methods return an ``APIResponse`` — the caller (step file)
    decides what to assert about status codes and body content.
    """

    def __init__(self, base_url: str, api_key: str | None = None, **kwargs) -> None:
        super().__init__(base_url, **kwargs)
        self._api_key = api_key or os.getenv(_API_KEY_ENV)
        if not self._api_key:
            log_warning(
                f"VEHICLE_API_KEY env var not set — x-api-key header will be empty. "
                f"Set {_API_KEY_ENV} in your environment or .env file."
            )

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def from_config(cls, config: dict) -> "VehicleAPIClient":
        """
        Construct from a loaded config.yaml dict.

        Priority for base URL:
          1. VEHICLE_API_BASE_URL env var
          2. config.environments.<env>.vehicle_api_url
          3. Raises VehicleClientConfigError
        """
        base_url = os.getenv(_BASE_URL_ENV)
        if not base_url:
            env = os.getenv("ENV", config.get("environment", "dev"))
            base_url = (
                config.get("environments", {})
                      .get(env, {})
                      .get("vehicle_api_url")
            )
        if not base_url:
            raise VehicleClientConfigError(
                f"Vehicle API base URL not configured. "
                f"Set {_BASE_URL_ENV} env var or "
                f"config.environments.<env>.vehicle_api_url in config.yaml."
            )

        retry_cfg = config.get("retry", {})
        return cls(
            base_url=base_url,
            max_retries=retry_cfg.get("max_attempts", 3),
            retry_backoff=retry_cfg.get("backoff_multiplier", 1.0),
        )

    # ------------------------------------------------------------------
    # Public API methods
    # ------------------------------------------------------------------

    def register_vehicles(
        self,
        partner_code: str,
        vin_list: list[str],
        transaction_id: str | None = None,
    ) -> APIResponse:
        """
        POST /bl4b/v1/vehicle/register

        A fresh transactionId is generated via ``generate_transaction_id()``
        before the request body is built, so it is logged before the HTTP call.

        Args:
            partner_code:    Platform partner code (e.g. "HBL4BP-006").
            vin_list:        One or more VINs to register.
            transaction_id:  Supply an explicit ID to override auto-generation
                             (useful in replay / idempotency tests).

        Returns:
            APIResponse — caller asserts on .status_code and .json().
        """
        txn_id = transaction_id or generate_transaction_id()
        log_info_emoji("🔑", f"transactionId → {txn_id}")

        req = VehicleRegistrationRequest(
            transaction_id=txn_id,
            partner_code=partner_code,
            vin_list=vin_list,
        )
        return self.post(
            _REGISTER_PATH,
            headers=self._auth_headers(),
            json_body=req.to_dict(),
        )

    def deregister_vehicles(
        self,
        partner_code: str,
        vin_list: list[str],
        transaction_id: str | None = None,
    ) -> APIResponse:
        """
        POST /bl4b/v1/vehicle/deregister

        A fresh transactionId is generated via ``generate_transaction_id()``
        before the request body is built, so it is logged before the HTTP call.

        Args:
            partner_code:    Platform partner code.
            vin_list:        One or more VINs to deregister.
            transaction_id:  Supply an explicit ID to override auto-generation.

        Returns:
            APIResponse — caller asserts on .status_code and .json().
        """
        txn_id = transaction_id or generate_transaction_id()
        log_info_emoji("🔑", f"transactionId → {txn_id}")

        req = VehicleDeregistrationRequest(
            transaction_id=txn_id,
            partner_code=partner_code,
            vin_list=vin_list,
        )
        return self.post(
            _DEREGISTER_PATH,
            headers=self._auth_headers(),
            json_body=req.to_dict(),
        )

    def register_vehicles_with_invalid_key(
        self,
        partner_code: str,
        vin_list: list[str],
    ) -> APIResponse:
        """Test helper — calls register with a deliberately wrong API key."""
        txn_id = generate_transaction_id()
        log_info_emoji("🔑", f"transactionId → {txn_id}  [invalid-key test]")

        req = VehicleRegistrationRequest(
            transaction_id=txn_id,
            partner_code=partner_code,
            vin_list=vin_list,
        )
        return self.post(
            _REGISTER_PATH,
            headers={"x-api-key": "invalid-key-for-testing", "Content-Type": "application/json"},
            json_body=req.to_dict(),
        )

    def register_without_required_field(
        self,
        missing_field: str,
        partner_code: str,
        vin_list: list[str],
    ) -> APIResponse:
        """Test helper — omits a required field to exercise 400 validation."""
        txn_id = generate_transaction_id()
        log_info_emoji("🔑", f"transactionId → {txn_id}  [missing-field test: {missing_field}]")

        body: dict[str, Any] = {
            "transactionId": txn_id,
            "partnerCode":   partner_code,
            "vinList":       [{"vin": v} for v in vin_list],
        }
        body.pop(missing_field, None)
        return self.post(
            _REGISTER_PATH,
            headers=self._auth_headers(),
            json_body=body,
        )

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _auth_headers(self) -> dict:
        return {
            "x-api-key":    self._api_key or "",
            "Content-Type": "application/json",
        }


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class VehicleClientConfigError(RuntimeError):
    """Raised when VehicleAPIClient cannot determine its base URL."""
